import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "./Providers/providers";
import { ThemeSelector } from "./Ui/ThemeSelector";
import { Toaster } from 'sonner';
import { dummyRequest } from "./lib/crudActions";

const inter = Poppins({ subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] });

export const metadata: Metadata = {
  title: "XPinterest",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await dummyRequest()
  return (
    <html className='' lang="en">
      <head>
      <link rel="icon" href="./favicon.ico" sizes="any" />
      </head>
      <body className={`${inter.className} antialiased`}>
        <Providers>
          {children}
          <Toaster richColors closeButton position="bottom-right" />
        </Providers>
        </body>
    </html>
  );
}
